In [2]:
!pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in c:\users\jagdish bugaliya\appdata\roaming\python\python313\site-packages (2.5.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\jagdish bugaliya\appdata\roaming\python\python313\site-packages (from geopy) (2.1)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: C:\Program Files\Python313\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:

import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Load  CSV file having state and district name 
df = pd.read_csv('place2001-2010.csv')  
df = df[['State_Name', 'District_Name']].drop_duplicates()

# Initialize geocoder
geolocator = Nominatim(user_agent="geoapi")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

# Create a location string
df['location'] = df['District_Name'] + ", " + df['State_Name'] + ", India"

# Apply geocoding
df['geo'] = df['location'].apply(geocode)
df['latitude'] = df['geo'].apply(lambda x: x.latitude if x else None)
df['longitude'] = df['geo'].apply(lambda x: x.longitude if x else None)

# Drop helper column 
df = df.drop(columns=['geo'])

# Save 
df.to_csv('districts_with_coordinates.csv', index=False)
print(df.head())

       State_Name  District_Name                              location  \
0  Andhra Pradesh      ANANTAPUR      ANANTAPUR, Andhra Pradesh, India
1  Andhra Pradesh       CHITTOOR       CHITTOOR, Andhra Pradesh, India
2  Andhra Pradesh  EAST GODAVARI  EAST GODAVARI, Andhra Pradesh, India
3  Andhra Pradesh         GUNTUR         GUNTUR, Andhra Pradesh, India
4  Andhra Pradesh         KADAPA         KADAPA, Andhra Pradesh, India

    latitude  longitude
0  14.678322  77.606504
1  13.325036  79.648061
2  16.995664  81.715438
3  16.291519  80.454159
4  14.475294  78.821686

In [5]:

# load coordinate file to review it 
coordinates=pd.read_csv("districts_with_coordinates.csv")
coordinates.head(20)

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,ANANTAPUR,"ANANTAPUR, Andhra Pradesh, India",14.678322,77.606504
1,Andhra Pradesh,CHITTOOR,"CHITTOOR, Andhra Pradesh, India",13.325036,79.648061
2,Andhra Pradesh,EAST GODAVARI,"EAST GODAVARI, Andhra Pradesh, India",16.995664,81.715438
3,Andhra Pradesh,GUNTUR,"GUNTUR, Andhra Pradesh, India",16.291519,80.454159
4,Andhra Pradesh,KADAPA,"KADAPA, Andhra Pradesh, India",14.475294,78.821686
5,Andhra Pradesh,KRISHNA,"KRISHNA, Andhra Pradesh, India",16.213547,81.027784
6,Andhra Pradesh,KURNOOL,"KURNOOL, Andhra Pradesh, India",15.830925,78.042537
7,Andhra Pradesh,PRAKASAM,"PRAKASAM, Andhra Pradesh, India",15.564196,80.006679
8,Andhra Pradesh,SPSR NELLORE,"SPSR NELLORE, Andhra Pradesh, India",14.557001,79.723478
9,Andhra Pradesh,SRIKAKULAM,"SRIKAKULAM, Andhra Pradesh, India",18.294931,83.893884
10,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",NaN,NaN
11,Andhra Pradesh,VIZIANAGARAM,"VIZIANAGARAM, Andhra Pradesh, India",18.114126,83.411439
12,Andhra Pradesh,WEST GODAVARI,"WEST GODAVARI, Andhra Pradesh, India",16.644303,81.588525
13,Arunachal Pradesh,ANJAW,"ANJAW, Arunachal Pradesh, India",28.155391,96.840724
14,Arunachal Pradesh,CHANGLANG,"CHANGLANG, Arunachal Pradesh, India",27.269880,96.060244
15,Arunachal Pradesh,DIBANG VALLEY,"DIBANG VALLEY, Arunachal Pradesh, India",28.829104,95.955410
16,Arunachal Pradesh,EAST KAMENG,"EAST KAMENG, Arunachal Pradesh, India",27.557781,93.075301
17,Arunachal Pradesh,EAST SIANG,"EAST SIANG, Arunachal Pradesh, India",28.074222,95.417815
18,Arunachal Pradesh,KURUNG KUMEY,"KURUNG KUMEY, Arunachal Pradesh, India",27.986368,93.157835
19,Arunachal Pradesh,LOHIT,"LOHIT, Arunachal Pradesh, India",28.035016,96.171352

In [6]:

# put 1 at place of null value of longitude to diffrenciate nan 
coordinates['longitude']=coordinates['longitude'].fillna(1)
coordinates.head(20)

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,ANANTAPUR,"ANANTAPUR, Andhra Pradesh, India",14.678322,77.606504
1,Andhra Pradesh,CHITTOOR,"CHITTOOR, Andhra Pradesh, India",13.325036,79.648061
2,Andhra Pradesh,EAST GODAVARI,"EAST GODAVARI, Andhra Pradesh, India",16.995664,81.715438
3,Andhra Pradesh,GUNTUR,"GUNTUR, Andhra Pradesh, India",16.291519,80.454159
4,Andhra Pradesh,KADAPA,"KADAPA, Andhra Pradesh, India",14.475294,78.821686
5,Andhra Pradesh,KRISHNA,"KRISHNA, Andhra Pradesh, India",16.213547,81.027784
6,Andhra Pradesh,KURNOOL,"KURNOOL, Andhra Pradesh, India",15.830925,78.042537
7,Andhra Pradesh,PRAKASAM,"PRAKASAM, Andhra Pradesh, India",15.564196,80.006679
8,Andhra Pradesh,SPSR NELLORE,"SPSR NELLORE, Andhra Pradesh, India",14.557001,79.723478
9,Andhra Pradesh,SRIKAKULAM,"SRIKAKULAM, Andhra Pradesh, India",18.294931,83.893884
10,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",NaN,1.000000
11,Andhra Pradesh,VIZIANAGARAM,"VIZIANAGARAM, Andhra Pradesh, India",18.114126,83.411439
12,Andhra Pradesh,WEST GODAVARI,"WEST GODAVARI, Andhra Pradesh, India",16.644303,81.588525
13,Arunachal Pradesh,ANJAW,"ANJAW, Arunachal Pradesh, India",28.155391,96.840724
14,Arunachal Pradesh,CHANGLANG,"CHANGLANG, Arunachal Pradesh, India",27.269880,96.060244
15,Arunachal Pradesh,DIBANG VALLEY,"DIBANG VALLEY, Arunachal Pradesh, India",28.829104,95.955410
16,Arunachal Pradesh,EAST KAMENG,"EAST KAMENG, Arunachal Pradesh, India",27.557781,93.075301
17,Arunachal Pradesh,EAST SIANG,"EAST SIANG, Arunachal Pradesh, India",28.074222,95.417815
18,Arunachal Pradesh,KURUNG KUMEY,"KURUNG KUMEY, Arunachal Pradesh, India",27.986368,93.157835
19,Arunachal Pradesh,LOHIT,"LOHIT, Arunachal Pradesh, India",28.035016,96.171352

In [7]:

# saving nan value data in different dataset
coord=coordinates[coordinates['longitude']==1]
coord.reset_index(drop=True, inplace=True)
# take list of district name to enter their latitude and longitude value manuly
coord_dic=list(coord['District_Name'])

In [8]:
coord

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",NaN,1.0
1,Gujarat,DOHAD,"DOHAD, Gujarat, India",NaN,1.0
2,Himachal Pradesh,LAHUL AND SPITI,"LAHUL AND SPITI, Himachal Pradesh, India",NaN,1.0
3,Jammu and Kashmir,LEH LADAKH,"LEH LADAKH, Jammu and Kashmir , India",NaN,1.0
4,Jharkhand,EAST SINGHBUM,"EAST SINGHBUM, Jharkhand, India",NaN,1.0
5,Karnataka,DAKSHIN KANNAD,"DAKSHIN KANNAD, Karnataka, India",NaN,1.0
6,Karnataka,UTTAR KANNAD,"UTTAR KANNAD, Karnataka, India",NaN,1.0
7,Punjab,FIROZEPUR,"FIROZEPUR, Punjab, India",NaN,1.0
8,Telangana,RANGAREDDI,"RANGAREDDI, Telangana , India",NaN,1.0
9,Uttar Pradesh,KUSHI NAGAR,"KUSHI NAGAR, Uttar Pradesh, India",NaN,1.0
10,Uttar Pradesh,SANT KABEER NAGAR,"SANT KABEER NAGAR, Uttar Pradesh, India",NaN,1.0
11,Uttarakhand,RUDRA PRAYAG,"RUDRA PRAYAG, Uttarakhand, India",NaN,1.0
12,Uttarakhand,UDAM SINGH NAGAR,"UDAM SINGH NAGAR, Uttarakhand, India",NaN,1.0
13,Uttarakhand,UTTAR KASHI,"UTTAR KASHI, Uttarakhand, India",NaN,1.0
14,West Bengal,24 PARAGANAS NORTH,"24 PARAGANAS NORTH, West Bengal, India",NaN,1.0
15,West Bengal,24 PARAGANAS SOUTH,"24 PARAGANAS SOUTH, West Bengal, India",NaN,1.0

In [ ]:
coord_dic

In [12]:
longitude_dict = {
    'VISAKHAPATANAM': 83.201610,
    'TAWANG': 91.924370,
    'DOHAD': 74.000000,
    'LEH LADAKH': 77.584020,
    'RAJAURI': 74.300000,
    'REASI': 74.830000,
    'SAMBA': 75.120000,
    'SHOPIAN': 74.830000,
    'SRINAGAR': 74.790000,
    'UDHAMPUR': 75.130000,
    'BOKARO': 86.150000,
    'EAST SINGHBUM': 86.180000,
    'GIRIDIH': 86.300000,
    'DAKSHIN KANNAD': 74.880000,
    'UTTAR KANNAD': 74.130000,
    'FIROZEPUR': 74.610000,
    'WEST DISTRICT': 88.150000,
    'RANGAREDDI': 78.400000,
    'KUSHI NAGAR': 83.890000,
    'SANT KABEER NAGAR': 83.070000,
    'RUDRA PRAYAG': 78.980000,
    'UDAM SINGH NAGAR': 79.400000,
    'UTTAR KASHI': 78.450000,
    '24 PARAGANAS NORTH': 88.450000,
    '24 PARAGANAS SOUTH': 88.430000
}

In [13]:

coord.shape

(16, 5)

In [14]:

key_li=list(longitude_dict.keys())
for i in range(coordinates.shape[0]):
    if coordinates['longitude'][i]==1:
        for j in range(len(key_li)):
            if coordinates['District_Name'][i]==key_li[j]:
                coordinates['longitude'][i]=longitude_dict[key_li[j]]

C:\Users\Jagdish Bugaliya\AppData\Local\Temp\ipykernel_21584\3619674443.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  coordinates['longitude'][i]=longitude_dict[key_li[j]]

In [15]:
coordinates.head(20)

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,ANANTAPUR,"ANANTAPUR, Andhra Pradesh, India",14.678322,77.606504
1,Andhra Pradesh,CHITTOOR,"CHITTOOR, Andhra Pradesh, India",13.325036,79.648061
2,Andhra Pradesh,EAST GODAVARI,"EAST GODAVARI, Andhra Pradesh, India",16.995664,81.715438
3,Andhra Pradesh,GUNTUR,"GUNTUR, Andhra Pradesh, India",16.291519,80.454159
4,Andhra Pradesh,KADAPA,"KADAPA, Andhra Pradesh, India",14.475294,78.821686
5,Andhra Pradesh,KRISHNA,"KRISHNA, Andhra Pradesh, India",16.213547,81.027784
6,Andhra Pradesh,KURNOOL,"KURNOOL, Andhra Pradesh, India",15.830925,78.042537
7,Andhra Pradesh,PRAKASAM,"PRAKASAM, Andhra Pradesh, India",15.564196,80.006679
8,Andhra Pradesh,SPSR NELLORE,"SPSR NELLORE, Andhra Pradesh, India",14.557001,79.723478
9,Andhra Pradesh,SRIKAKULAM,"SRIKAKULAM, Andhra Pradesh, India",18.294931,83.893884
10,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",NaN,1.000000
11,Andhra Pradesh,VIZIANAGARAM,"VIZIANAGARAM, Andhra Pradesh, India",18.114126,83.411439
12,Andhra Pradesh,WEST GODAVARI,"WEST GODAVARI, Andhra Pradesh, India",16.644303,81.588525
13,Arunachal Pradesh,ANJAW,"ANJAW, Arunachal Pradesh, India",28.155391,96.840724
14,Arunachal Pradesh,CHANGLANG,"CHANGLANG, Arunachal Pradesh, India",27.269880,96.060244
15,Arunachal Pradesh,DIBANG VALLEY,"DIBANG VALLEY, Arunachal Pradesh, India",28.829104,95.955410
16,Arunachal Pradesh,EAST KAMENG,"EAST KAMENG, Arunachal Pradesh, India",27.557781,93.075301
17,Arunachal Pradesh,EAST SIANG,"EAST SIANG, Arunachal Pradesh, India",28.074222,95.417815
18,Arunachal Pradesh,KURUNG KUMEY,"KURUNG KUMEY, Arunachal Pradesh, India",27.986368,93.157835
19,Arunachal Pradesh,LOHIT,"LOHIT, Arunachal Pradesh, India",28.035016,96.171352

In [17]:

latitude_dict = {
    'VISAKHAPATANAM': 17.680090,
    'TAWANG': 27.574170,
    'DOHAD': 22.900000,
    'LEH LADAKH': 34.165040,
    'RAJAURI': 33.375000,
    'REASI': 33.080000,
    'SAMBA': 32.570000,
    'SHOPIAN': 33.720000,
    'SRINAGAR': 34.090000,
    'UDHAMPUR': 32.930000,
    'BOKARO': 23.670000,
    'EAST SINGHBUM': 22.780000,
    'GIRIDIH': 24.180000,
    'DAKSHIN KANNAD': 12.870000,
    'UTTAR KANNAD': 14.800000,
    'FIROZEPUR': 30.930000,
    'WEST DISTRICT': 27.300000,
    'RANGAREDDI': 17.300000,
    'KUSHI NAGAR': 26.740000,
    'SANT KABEER NAGAR': 26.780000,
    'RUDRA PRAYAG': 30.280000,
    'UDAM SINGH NAGAR': 29.000000,
    'UTTAR KASHI': 30.730000,
    '24 PARAGANAS NORTH': 22.650000,
    '24 PARAGANAS SOUTH': 22.180000
}

In [19]:

coordinates['latitude']=coordinates['latitude'].fillna(1)

In [20]:

coordinates.head(20)

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,ANANTAPUR,"ANANTAPUR, Andhra Pradesh, India",14.678322,77.606504
1,Andhra Pradesh,CHITTOOR,"CHITTOOR, Andhra Pradesh, India",13.325036,79.648061
2,Andhra Pradesh,EAST GODAVARI,"EAST GODAVARI, Andhra Pradesh, India",16.995664,81.715438
3,Andhra Pradesh,GUNTUR,"GUNTUR, Andhra Pradesh, India",16.291519,80.454159
4,Andhra Pradesh,KADAPA,"KADAPA, Andhra Pradesh, India",14.475294,78.821686
5,Andhra Pradesh,KRISHNA,"KRISHNA, Andhra Pradesh, India",16.213547,81.027784
6,Andhra Pradesh,KURNOOL,"KURNOOL, Andhra Pradesh, India",15.830925,78.042537
7,Andhra Pradesh,PRAKASAM,"PRAKASAM, Andhra Pradesh, India",15.564196,80.006679
8,Andhra Pradesh,SPSR NELLORE,"SPSR NELLORE, Andhra Pradesh, India",14.557001,79.723478
9,Andhra Pradesh,SRIKAKULAM,"SRIKAKULAM, Andhra Pradesh, India",18.294931,83.893884
10,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",1.000000,1.000000
11,Andhra Pradesh,VIZIANAGARAM,"VIZIANAGARAM, Andhra Pradesh, India",18.114126,83.411439
12,Andhra Pradesh,WEST GODAVARI,"WEST GODAVARI, Andhra Pradesh, India",16.644303,81.588525
13,Arunachal Pradesh,ANJAW,"ANJAW, Arunachal Pradesh, India",28.155391,96.840724
14,Arunachal Pradesh,CHANGLANG,"CHANGLANG, Arunachal Pradesh, India",27.269880,96.060244
15,Arunachal Pradesh,DIBANG VALLEY,"DIBANG VALLEY, Arunachal Pradesh, India",28.829104,95.955410
16,Arunachal Pradesh,EAST KAMENG,"EAST KAMENG, Arunachal Pradesh, India",27.557781,93.075301
17,Arunachal Pradesh,EAST SIANG,"EAST SIANG, Arunachal Pradesh, India",28.074222,95.417815
18,Arunachal Pradesh,KURUNG KUMEY,"KURUNG KUMEY, Arunachal Pradesh, India",27.986368,93.157835
19,Arunachal Pradesh,LOHIT,"LOHIT, Arunachal Pradesh, India",28.035016,96.171352

In [21]:

key_la=list(latitude_dict.keys())
for i in range(coordinates.shape[0]):
    if coordinates['latitude'][i]==1:
        for j in range(len(key_la)):
            if coordinates['District_Name'][i]==key_la[j]:
                coordinates['latitude'][i]=latitude_dict[key_la[j]]

C:\Users\Jagdish Bugaliya\AppData\Local\Temp\ipykernel_21584\3462931694.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  coordinates['latitude'][i]=latitude_dict[key_la[j]]

In [22]:
coordinates.head(20)

,State_Name,District_Name,location,latitude,longitude
0,Andhra Pradesh,ANANTAPUR,"ANANTAPUR, Andhra Pradesh, India",14.678322,77.606504
1,Andhra Pradesh,CHITTOOR,"CHITTOOR, Andhra Pradesh, India",13.325036,79.648061
2,Andhra Pradesh,EAST GODAVARI,"EAST GODAVARI, Andhra Pradesh, India",16.995664,81.715438
3,Andhra Pradesh,GUNTUR,"GUNTUR, Andhra Pradesh, India",16.291519,80.454159
4,Andhra Pradesh,KADAPA,"KADAPA, Andhra Pradesh, India",14.475294,78.821686
5,Andhra Pradesh,KRISHNA,"KRISHNA, Andhra Pradesh, India",16.213547,81.027784
6,Andhra Pradesh,KURNOOL,"KURNOOL, Andhra Pradesh, India",15.830925,78.042537
7,Andhra Pradesh,PRAKASAM,"PRAKASAM, Andhra Pradesh, India",15.564196,80.006679
8,Andhra Pradesh,SPSR NELLORE,"SPSR NELLORE, Andhra Pradesh, India",14.557001,79.723478
9,Andhra Pradesh,SRIKAKULAM,"SRIKAKULAM, Andhra Pradesh, India",18.294931,83.893884
10,Andhra Pradesh,VISAKHAPATANAM,"VISAKHAPATANAM, Andhra Pradesh, India",1.000000,1.000000
11,Andhra Pradesh,VIZIANAGARAM,"VIZIANAGARAM, Andhra Pradesh, India",18.114126,83.411439
12,Andhra Pradesh,WEST GODAVARI,"WEST GODAVARI, Andhra Pradesh, India",16.644303,81.588525
13,Arunachal Pradesh,ANJAW,"ANJAW, Arunachal Pradesh, India",28.155391,96.840724
14,Arunachal Pradesh,CHANGLANG,"CHANGLANG, Arunachal Pradesh, India",27.269880,96.060244
15,Arunachal Pradesh,DIBANG VALLEY,"DIBANG VALLEY, Arunachal Pradesh, India",28.829104,95.955410
16,Arunachal Pradesh,EAST KAMENG,"EAST KAMENG, Arunachal Pradesh, India",27.557781,93.075301
17,Arunachal Pradesh,EAST SIANG,"EAST SIANG, Arunachal Pradesh, India",28.074222,95.417815
18,Arunachal Pradesh,KURUNG KUMEY,"KURUNG KUMEY, Arunachal Pradesh, India",27.986368,93.157835
19,Arunachal Pradesh,LOHIT,"LOHIT, Arunachal Pradesh, India",28.035016,96.171352

In [23]:

coordinates.isnull().sum()

State_Name       0
District_Name    0
location         0
latitude         0
longitude        0
dtype: int64

In [24]:

coordinates=coordinates.drop('location',axis=1)
# saving coordinate file 
coordinates.to_csv("filled_coordinates.csv",index=False)